version: '3.7'
services:
  server:
    image: ehenoma/jsheets:latest
    restart: always
    environment:
      JSHEETS_SERVER_PORT: 8080
      JSHEETS_MONGODB_URI: mongodb://root:root@document-store/jsheets?authSource=admin
      JSHEETS_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    ports:
      - "8080:8080"
    depends_on:
      - document-store
    networks:
      - document-store
      - zookeeper
      - runtime
  document-store:
    image: mongo:latest
    container_name: document-store
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - document-store
  zookeeper:
    image: zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
    networks:
      - zookeeper
  runtime:
    image: ehenoma/jsheets-runtime:latest
    restart: always
    container_name: runtime
    hostname: runtime
    build:
      context: ../../
      dockerfile: ./runtime/deploy/Dockerfile
    environment:
      JSHEETS_RUNTIME_SERVER_PORT: 8080
      JSHEETS_RUNTIME_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      JSHEETS_RUNTIME_SERVICE_ADVERTISED_HOST: runtime:8080
      JSHEETS_RUNTIME_MONITORING_BACKEND: influx
      JSHEETS_RUNTIME_MONITORING_INFLUX_URI: "http://influxdb:8086"
      JSHEETS_RUNTIME_MONITORING_INFLUX_USER_NAME: ${INFLUXDB_USERNAME}
      JSHEETS_RUNTIME_MONITORING_INFLUX_PASSWORD: ${INFLUXDB_PASSWORD}
    depends_on:
      - zookeeper
    networks:
      - zookeeper
      - runtime
      - influxdb
networks:
  document-store:
  zookeeper:
  runtime:
