apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: jsheets
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 3
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ehenoma/jsheets:latest
          ports:
            - containerPort: 8080
              hostPort: 8080
          env:
            - name: JSHEETS_SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: jsheets
spec:
  selector:
    app: server
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-ingress
  namespace: jsheets
spec:
  rules:
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: server-service
